// Package source loads the source files a function was compiled from and
// relates their lines to instruction indices.
package source

import (
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"

	"loov.dev/lensm/internal/disasm"
)

// Ref is a source position referenced by one or more instructions.
type Ref struct {
	File string
	Line int
}

// Refs collects, per source position, the indices of the instructions
// compiled from it.
type Refs map[Ref]*disasm.LineSet

// Add records that instruction index was compiled from file:line.
// Positions without a file, or inside compiler-generated code, are ignored.
func (refs Refs) Add(file string, line int, index int) {
	if file == "" || file == "<autogenerated>" {
		return
	}
	set, ok := refs[Ref{file, line}]
	if !ok {
		set = &disasm.LineSet{}
		refs[Ref{file, line}] = set
	}
	set.Add(index)
}

// Load reads the referenced lines of each file with context lines around
// them and fills SourceBlock.Related from refs. symbolFile sorts first.
func Load(refs Refs, symbolFile string, context int) []disasm.Source {
	needed := map[string]*disasm.LineSet{}
	for ref := range refs {
		set, ok := needed[ref.File]
		if !ok {
			set = &disasm.LineSet{}
			needed[ref.File] = set
		}
		set.Add(ref.Line)
	}
	sources := loadLines(needed, symbolFile, context)
	for i := range sources {
		src := &sources[i]
		for k := range src.Blocks {
			block := &src.Blocks[k]
			block.Related = make([][]disasm.LineRange, len(block.Lines))
			for line := block.From; line < block.From+len(block.Lines); line++ {
				if set, ok := refs[Ref{src.File, line}]; ok {
					block.Related[line-block.From] = set.RangesZero()
				}
			}
		}
	}
	return sources
}

var rxEnvVariable = regexp.MustCompile(`\$[a-zA-Z_]+[a-zA-Z0-9_]+\b`)

func replaceEnvironmentVariables(s string) string {
	return rxEnvVariable.ReplaceAllStringFunc(s, func(env string) string {
		replacement := os.Getenv(env[1:])
		if replacement != "" {
			return replacement
		}
		return env
	})
}

// loadLines loads the specified line sets.
func loadLines(needed map[string]*disasm.LineSet, symbolFile string, context int) []disasm.Source {
	var sources []disasm.Source
	for file, set := range needed {
		data, err := os.ReadFile(replaceEnvironmentVariables(file))
		if err != nil {
			// TODO: should we create a stub source block instead?
			fmt.Fprintf(os.Stderr, "unable to load source from %q: %v\n", file, err)
			continue
		}
		lines := strings.Split(string(data), "\n")
		source := disasm.Source{
			File: file,
		}
		for _, r := range set.Ranges(context) {
			// The file may have been edited since the build; clamp both
			// ends rather than trusting the line table.
			from, to := r.From-1, min(r.To-1, len(lines))
			if from >= to {
				continue
			}
			lineBlock := lines[from:to]
			for i, v := range lineBlock {
				lineBlock[i] = strings.ReplaceAll(v, "\t", "    ")
			}

			source.Blocks = append(source.Blocks, disasm.SourceBlock{
				LineRange: r,
				Lines:     lineBlock,
			})
		}
		sources = append(sources, source)
	}

	// Sort the sources and prioritize the file where the main symbol is located.
	sort.Slice(sources, func(i, j int) bool {
		if sources[i].File == symbolFile {
			return true
		}
		if sources[j].File == symbolFile {
			return false
		}
		return sources[i].File < sources[j].File
	})

	return sources
}
